// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../../../main.h"
#include "../../../plugins/BLEScalePlugin.h"
#include "ui.h"
#include <Arduino.h>

// Flag to track if volumetric hold was triggered
static bool volumetricHoldTriggered = false;

void onBrewCancel(lv_event_t *e) {
    controller.deactivate();
    controller.clear();
}

void onBrewStart(lv_event_t *e) { controller.activate(); }

void onBrewTempLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerTemp();
}

void onBrewTempRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseTemp();
}

void onBrewTimeLower(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.lowerBrewTarget();
}

void onBrewTimeRaise(lv_event_t *e) {
    controller.getUI()->markProfileDirty();
    controller.raiseBrewTarget();
}

void onSteamTempLower(lv_event_t *e) { controller.lowerTemp(); }

void onSteamTempRaise(lv_event_t *e) { controller.raiseTemp(); }

void onBrewScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onWaterScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_WATER);
    controller.deactivate();
}

void onSteamScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
    controller.setMode(MODE_STEAM);
    controller.deactivate();
}

// --- Mode selector (Brew/Steam/Water indicator + tappable alternatives) -------
// The active mode is shown as a coloured "pill" at the top of a control screen;
// the two other modes flank it as tappable labels that switch mode directly. The
// flank's target mode is stored in its user_data by DefaultUI::applyModeSelector.
void onModeSelect(int mode) {
    // [mode-selector] Anti-mistouch: ignore flank taps only during an active BREW so
    // an accidental touch can't cancel the shot. Steam/water are quick manual
    // operations where switching freely is fine, so they are NOT locked.
    if (controller.isActive() && controller.getMode() == MODE_BREW) {
        return;
    }
    controller.deactivate();
    if (mode == MODE_STEAM) {
        controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
        controller.setMode(MODE_STEAM);
    } else if (mode == MODE_WATER) {
        controller.getUI()->changeScreen(&ui_SimpleProcessScreen, &ui_SimpleProcessScreen_screen_init);
        controller.setMode(MODE_WATER);
    } else {
        controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
        controller.setMode(MODE_BREW);
    }
}

static void ui_event_mode_flank(lv_event_t *e) {
    if (lv_event_get_code(e) != LV_EVENT_CLICKED)
        return;
    lv_obj_t *label = lv_event_get_target(e);
    onModeSelect((int)(intptr_t)lv_obj_get_user_data(label));
}

lv_obj_t *ui_create_mode_pill(lv_obj_t *parent) {
    lv_obj_t *pill = lv_label_create(parent);
    lv_obj_set_width(pill, LV_SIZE_CONTENT);
    lv_obj_set_height(pill, LV_SIZE_CONTENT);
    lv_obj_set_x(pill, 0);
    lv_obj_set_y(pill, -150);
    lv_obj_set_align(pill, LV_ALIGN_CENTER);
    lv_label_set_text(pill, "Brew");
    lv_obj_set_style_text_color(pill, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(pill, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(pill, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(pill, lv_color_hex(0xB0651A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(pill, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_hor(pill, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_ver(pill, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    return pill;
}

lv_obj_t *ui_create_mode_flank(lv_obj_t *parent, int x_offset) {
    lv_obj_t *label = lv_label_create(parent);
    lv_obj_set_width(label, LV_SIZE_CONTENT);
    lv_obj_set_height(label, LV_SIZE_CONTENT);
    lv_obj_set_x(label, x_offset);
    lv_obj_set_y(label, -108);
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_label_set_text(label, "");
    lv_obj_set_style_text_color(label, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_ext_click_area(label, 18);
    lv_obj_add_event_cb(label, ui_event_mode_flank, LV_EVENT_ALL, NULL);
    return label;
}

void onWakeup(lv_event_t *e) {
    if (controller.isUpdating() || controller.isErrorState() || controller.isAutotuning() ||
        !controller.getClientController()->isConnected()) {
        return;
    }
    controller.getUI()->changeScreen(&ui_BrewScreen, &ui_BrewScreen_screen_init);
    controller.deactivate();
    controller.setMode(MODE_BREW);
}

void onLoadStarted(lv_event_t *e) {}

void onStandby(lv_event_t *e) { controller.activateStandby(); }

void onGrindToggle(lv_event_t *e) { controller.isGrindActive() ? controller.deactivateGrind() : controller.activateGrind(); }

void onGrindTimeLower(lv_event_t *e) { controller.lowerGrindTarget(); }

void onGrindTimeRaise(lv_event_t *e) { controller.raiseGrindTarget(); }

void onMenuClick(lv_event_t *e) {
    controller.deactivate();
    controller.setMode(MODE_BREW);
    controller.getUI()->changeScreen(&ui_MenuScreen, &ui_MenuScreen_screen_init);
}

void onGrindScreen(lv_event_t *e) {
    controller.getUI()->changeScreen(&ui_GrindScreen, &ui_GrindScreen_screen_init);
    controller.setMode(MODE_GRIND);
}

void onVolumetricClick(lv_event_t *e) {}

void onPreviousProfile(lv_event_t *e) { controller.getUI()->onPreviousProfile(); }

void onNextProfile(lv_event_t *e) { controller.getUI()->onNextProfile(); }

void onProfileLoad(lv_event_t *e) { controller.getUI()->onProfileSelect(); }

void onProfileSelect(lv_event_t *e) { controller.getUI()->onProfileSwitch(); }

void onFlush(lv_event_t *e) { controller.onFlush(); }

void onSimpleProcessToggle(lv_event_t *e) {
    if (controller.getMode() != MODE_STEAM) {
        controller.isActive() ? controller.deactivate() : controller.activate();
    }
}

void onProfileScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_ProfileScreen_previousProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_nextProfileBtn, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_chooseButton, 30);
    lv_obj_set_ext_click_area(ui_ProfileScreen_ImgButton1, 20);
}

void onMenuScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_MenuScreen_btnBrew, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_btnSteam, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_waterBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_grindBtn, 15);
    lv_obj_set_ext_click_area(ui_MenuScreen_standbyButton, 20);
}

void onBrewScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_BrewScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_profileSelectBtn, 25);
    lv_obj_set_ext_click_area(ui_BrewScreen_ImgButton5, 20);
    lv_obj_set_ext_click_area(ui_BrewScreen_upDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downDurationButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_upTempButton, 15);
    lv_obj_set_ext_click_area(ui_BrewScreen_downTempButton, 15);
}

void onSimpleProcessScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_downTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_upTempButton, 40);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_goButton, 25);
    lv_obj_set_ext_click_area(ui_SimpleProcessScreen_ImgButton6, 20);
}

void onStatusScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_StatusScreen_pauseButton, 25);
    lv_obj_set_ext_click_area(ui_StatusScreen_ImgButton8, 20);
}

void onGrindScreenLoad(lv_event_t *e) {
    lv_obj_set_ext_click_area(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_ext_click_area(ui_GrindScreen_startButton, 25);
    lv_obj_set_ext_click_area(ui_GrindScreen_ImgButton2, 20);
}

void onProfileSettings(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Settings); }

void onProfileSave(lv_event_t *e) {
    controller.onProfileSave();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onProfileAccept(lv_event_t *e) { controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew); }

void onProfileSaveAsNew(lv_event_t *e) {
    controller.onProfileSaveAsNew();
    controller.getUI()->markProfileClean();
    controller.getUI()->changeBrewScreenMode(BrewScreenState::Brew);
}

void onVolumetricHold(lv_event_t *e) {
    // Set flag to prevent click from firing when button is released
    volumetricHoldTriggered = true;

    controller.getClientController()->tare();
    BLEScales.tare();
}

void onVolumetricDelete(lv_event_t *e) { controller.getUI()->onVolumetricDelete(); }
